version: "3.7"
services:
  redis-producer:
    build: producer/.
    environment:
      - "NODE_ENV=local"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    ports:
      - "8000:8000"
    container_name: redis-producer
    depends_on:
      - redis
  redis-consumer:
    build: consumer/.
    environment:
      - "NODE_ENV=local"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
      - "REDIS_QUE=dowork"
    depends_on:
      - redis
  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
